name: Connect Docker Image to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Azure service principal credentials

    - name: Configure Azure Web App to use Docker image
      run: |
        az webapp config container set \
          --name tasty-routes \
          --resource-group tastyapp \
          --docker-custom-image-name index.docker.io/obeed1/tasty-routes:latest \
          --docker-registry-server-url https://index.docker.io \
          --docker-registry-server-user ${{ secrets.DOCKER_HUB_USERNAME }} \
          --docker-registry-server-password ${{ secrets.DOCKER_HUB_PASSWORD }}
